baseURL = 'https://rdwiananda-afk.github.io/' # Nanti disesuaikan pas deploy
languageCode = 'id-ID'
title = "What I've Done"
theme = 'console'

[params]
  # Ganti nama user di sini biar keren pas loading
  console_cursor = "rdwiananda@mac:~$" 
  animate_typing = true
  accent_color = "#fdda0e" # Warna kuning terminal

[[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "photos"
    name = "Photos"
    url = "/photos/"
    weight = 3